# Generated by Django 2.2 on 2019-07-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourmiliere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
