# Generated by Django 2.2 on 2019-07-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourmiliere', '0004_attitue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
