# Generated by Django 2.2 on 2019-07-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourmiliere', '0005_auto_20190721_0557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attitue',
            new_name='Attitude',
        ),
    ]
